name: lce_codegen
description: codegen for lce
version: 0.1.0
homepage: https://github.com/TshineZheng/flutter_lce

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  source_gen: '>=1.0.0 <=1.2.2'
  build: '>=2.0.0 <2.3.0'
  analyzer: '>=2.0.0 <5.0.0'
  source_helper: ^1.3.2
  lce: ">=0.1.0 <=0.2.0"
  # mobx_codegen: ^2.1.1
  # code_builder: ^4.3.0

# dependency_overrides:
#   lce:
#     path: ../lce/
  
dev_dependencies:
  # flutter_test:
  #   sdk: flutter
  flutter_lints: ^2.0.0


# flutter: