name: lce
description: Flutter LCE(Load Content Error) 
version: 0.1.0
homepage: https://github.com/TshineZheng/flutter_lce

environment:
  sdk: '>=2.18.2 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  mobx: ">=2.0.0 <2.2.0"
  flutter_mobx: ">=2.0.0 <2.2.0"
  meta: ^1.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mobx_codegen: ">=2.0.0"
  build_runner: any

flutter:
